services:
  mongodb:
    image: mongo:latest
    ports:
      - "27021:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
volumes:
  mongodb_data: